notes: |
  Each section contains the same initial HTML. 
  
  .
  
  These scripts perform the restructuring:
    
  &#60;script type="text/javascript" src="../../js/accordion-from-content.js"></script>
    
  &#60;script type="text/javascript">
  
    $(document).ready(function(){
    
    	accordionify({
    		id: "#item-118"
    	});
    	accordionify({
    		id: "#item-119",
    		headingLevel: "h4"
    	});
    });
    
    &#60;/script>
