preview: '@blank-page-main'
notes: At mobile breakpoints, the left nav collapses into a clickable dropdown.
context:
  friendly_url: www.example2.com
  left_nav:
    parent:
      name: Scams and Fraud
      friendly_url: www.example.com
    items:
      - name: Common Scams and Frauds
        friendly_url: www.example1.com
      - name: Housing Scams
        friendly_url: www.example2.com
      - name: Identify and Report Scams and Frauds
        friendly_url: www.example3.com
      - name: Identity Theft
        friendly_url: www.example4.com
      - name: Online Safety
        friendly_url: www.example5.com
      - name: Privacy
        friendly_url: www.example6.com
variants:
  - name: default
  - name: not-default
    notes: friendly_url matches the 2nd link, but we've set highlighted_url to match the 4th link
    context:
      left_nav:
        highlighted_url: www.example4.com

