preview: '@blank-page-main'
title: Modal
name: Modal
order: 0
status: wip
notes:
  Example - https://www.usa.gov/education?source=kids
  <br>
  <br>
  This modal window will be used for emergency messages and 
  to inform users when the've been redirected from our other sites.
  The emergency version has slightly different styles.
  <br>
  It will only be used on the homepage.
  <br>
  <br>
  We use javascript to store a cookie when a user closes the modal.
  If the cookie is detected with the same data-id, then the modal will not show.
context:
  modal:
    status: #active #leave blank to not show the modal. Use "active" to view modal
    id: emergency-modal #leave blank for default styles. Use "emergency-modal" for emergency styles
    heading: Ack! It's a Zombie Apocalypse
    text: This is test content. Check back here in the case of an actual zombie apocalypse.
