preview: '@blank-page-main'
title: VOC Modal
name: VOC Modal
order: 0
status: wip
notes:
  The VOC Survey Modal is designed to display at random upon page load to users who havent been shown the survey recently.
  <br>
  <br>
  To make the modal display for testing, set a breakpoint in invitation.js around line 33 and refesh the page. Then run loadModal() from the command line.
  
context:
  voc:
    status: active #leave blank to not show the modal. Use "active" to view modal
