preview: '@blank-page-main'
notes: 
context:
  whats_on_this_page:
    - name: Common Scams and Frauds
      id: www.example1.com
    - name: Housing Scams
      id: www.example2.com
    - name: Identify and Report Scams and Frauds
      id: www.example3.com
    - name: Identity Theft
      id: www.example4.com
    - name: Online Safety
      id: www.example5.com
    - name: Privacy
      id: www.example6.com